# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
    exclude: |
      (?x)^(
        grid_common/lua-5.4.3/|
        grid_esp/bootloader/|
        grid_make/thirdparty/|
        grid_make/samd51a/|
        grid_make/hal/|
        grid_make/hpl/|
        grid_make/hri/|
        grid_make/stdio_redirect/|
        grid_make/CMSIS/
      )
  - id: end-of-file-fixer
    exclude: |
      (?x)^(
        grid_common/lua-5.4.3/|
        grid_esp/bootloader/|
        grid_make/thirdparty/|
        grid_make/samd51a/|
        grid_make/hal/|
        grid_make/hpl/|
        grid_make/hri/|
        grid_make/stdio_redirect/|
        grid_make/CMSIS/
      )

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    args: [-w]
    exclude: |
      (?x)^(
        grid_common/lua-5.4.3/|
        grid_esp/bootloader/|
        grid_make/thirdparty/|
        grid_make/samd51a/|
        grid_make/hal/|
        grid_make/hpl/|
        grid_make/hri/|
        grid_make/stdio_redirect/|
        grid_make/CMSIS/
      )
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.6
  hooks:
  - id: clang-format
    exclude: |
      (?x)^(
        grid_common/lua-5.4.3/|
        grid_esp/bootloader/|
        grid_make/thirdparty/|
        grid_make/samd51a/|
        grid_make/hal/|
        grid_make/hpl/|
        grid_make/hri/|
        grid_make/stdio_redirect/|
        grid_make/CMSIS/|
        grid_make/usb/|
        grid_make/config/|
        grid_make/examples/
      )

- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v2.1.0
  hooks:
    - id: stylua # or stylua-system / stylua-github
