GRID_DEFINES = -DGRID

SUB_DIRS +=  \
\
usb/class/midi/device \
usb/class/midi \
grid/lua \
grid \
thirdparty/Lua/lua-5.4.3/src \
\

OBJS +=  \
\
usb/class/midi/device/audiodf_midi.o \
usb/class/midi/usb_protocol_midi.o \
grid/grid_ain.o \
grid/grid_buf.o \
grid/grid_d51.o \
grid/grid_debug.o \
grid/grid_default.o \
grid/grid_expr.o \
grid/grid_hardwaretest.o \
grid/grid_led.o \
grid/grid_module.o \
grid/grid_module_bu16.o \
grid/grid_module_en16.o \
grid/grid_module_pbf4.o \
grid/grid_module_po16.o \
grid/grid_module_ef44.o \
grid/grid_msg.o \
grid/grid_nvm.o \
grid/grid_protocol.o \
grid/grid_sys.o \
grid/grid_ui.o \
grid/grid_unittest.o \
grid/grid_usb.o \
grid/grid_lua_api.o \
thirdparty/Lua/lua-5.4.3/src/lapi.o \
thirdparty/Lua/lua-5.4.3/src/lctype.o \
thirdparty/Lua/lua-5.4.3/src/lfunc.o \
thirdparty/Lua/lua-5.4.3/src/lmathlib.o \
thirdparty/Lua/lua-5.4.3/src/loslib.o \
thirdparty/Lua/lua-5.4.3/src/ltable.o \
thirdparty/Lua/lua-5.4.3/src/lundump.o \
thirdparty/Lua/lua-5.4.3/src/lauxlib.o \
thirdparty/Lua/lua-5.4.3/src/ldblib.o \
thirdparty/Lua/lua-5.4.3/src/lgc.o \
thirdparty/Lua/lua-5.4.3/src/lmem.o \
thirdparty/Lua/lua-5.4.3/src/lparser.o \
thirdparty/Lua/lua-5.4.3/src/ltablib.o \
thirdparty/Lua/lua-5.4.3/src/lutf8lib.o \
thirdparty/Lua/lua-5.4.3/src/lbaselib.o \
thirdparty/Lua/lua-5.4.3/src/ldebug.o \
thirdparty/Lua/lua-5.4.3/src/linit.o \
thirdparty/Lua/lua-5.4.3/src/loadlib.o \
thirdparty/Lua/lua-5.4.3/src/lstate.o \
thirdparty/Lua/lua-5.4.3/src/ltm.o \
thirdparty/Lua/lua-5.4.3/src/lvm.o \
thirdparty/Lua/lua-5.4.3/src/lcode.o \
thirdparty/Lua/lua-5.4.3/src/ldo.o \
thirdparty/Lua/lua-5.4.3/src/liolib.o \
thirdparty/Lua/lua-5.4.3/src/lobject.o \
thirdparty/Lua/lua-5.4.3/src/lstring.o \
thirdparty/Lua/lua-5.4.3/src/lzio.o \
thirdparty/Lua/lua-5.4.3/src/llex.o \
thirdparty/Lua/lua-5.4.3/src/lopcodes.o \
thirdparty/Lua/lua-5.4.3/src/ldump.o \
thirdparty/Lua/lua-5.4.3/src/lstrlib.o \
thirdparty/Lua/lua-5.4.3/src/lcorolib.o \

# thirdparty/Lua/lua-5.4.3/src/luac.o \
# thirdparty/Lua/lua-5.4.3/src/lua.o \



OBJS_AS_ARGS +=  \
\
"usb/class/midi/device/audiodf_midi.o" \
"usb/class/midi/usb_protocol_midi.o" \
"grid/grid_ain.o" \
"grid/grid_buf.o" \
"grid/grid_d51.o" \
"grid/grid_debug.o" \
"grid/grid_default.o" \
"grid/grid_expr.o" \
"grid/grid_hardwaretest.o" \
"grid/grid_led.o" \
"grid/grid_module.o" \
"grid/grid_module_bu16.o" \
"grid/grid_module_en16.o" \
"grid/grid_module_pbf4.o" \
"grid/grid_module_po16.o" \
"grid/grid_module_ef44.o" \
"grid/grid_msg.o" \
"grid/grid_nvm.o" \
"grid/grid_protocol.o" \
"grid/grid_sys.o" \
"grid/grid_ui.o" \
"grid/grid_unittest.o" \
"grid/grid_usb.o" \
"grid/grid_lua_api.o" \
"thirdparty/Lua/lua-5.4.3/src/lapi.o" \
"thirdparty/Lua/lua-5.4.3/src/lctype.o" \
"thirdparty/Lua/lua-5.4.3/src/lfunc.o" \
"thirdparty/Lua/lua-5.4.3/src/lmathlib.o" \
"thirdparty/Lua/lua-5.4.3/src/loslib.o" \
"thirdparty/Lua/lua-5.4.3/src/ltable.o" \
"thirdparty/Lua/lua-5.4.3/src/lundump.o" \
"thirdparty/Lua/lua-5.4.3/src/lauxlib.o" \
"thirdparty/Lua/lua-5.4.3/src/ldblib.o" \
"thirdparty/Lua/lua-5.4.3/src/lgc.o" \
"thirdparty/Lua/lua-5.4.3/src/lmem.o" \
"thirdparty/Lua/lua-5.4.3/src/lparser.o" \
"thirdparty/Lua/lua-5.4.3/src/ltablib.o" \
"thirdparty/Lua/lua-5.4.3/src/lutf8lib.o" \
"thirdparty/Lua/lua-5.4.3/src/lbaselib.o" \
"thirdparty/Lua/lua-5.4.3/src/ldebug.o" \
"thirdparty/Lua/lua-5.4.3/src/linit.o" \
"thirdparty/Lua/lua-5.4.3/src/loadlib.o" \
"thirdparty/Lua/lua-5.4.3/src/lstate.o" \
"thirdparty/Lua/lua-5.4.3/src/ltm.o" \
"thirdparty/Lua/lua-5.4.3/src/lvm.o" \
"thirdparty/Lua/lua-5.4.3/src/lcode.o" \
"thirdparty/Lua/lua-5.4.3/src/ldo.o" \
"thirdparty/Lua/lua-5.4.3/src/liolib.o" \
"thirdparty/Lua/lua-5.4.3/src/lobject.o" \
"thirdparty/Lua/lua-5.4.3/src/lstring.o" \
"thirdparty/Lua/lua-5.4.3/src/lzio.o" \
"thirdparty/Lua/lua-5.4.3/src/llex.o" \
"thirdparty/Lua/lua-5.4.3/src/lopcodes.o" \
"thirdparty/Lua/lua-5.4.3/src/ldump.o" \
"thirdparty/Lua/lua-5.4.3/src/lstrlib.o" \
"thirdparty/Lua/lua-5.4.3/src/lcorolib.o" \

# "thirdparty/Lua/lua-5.4.3/src/luac.o" \
# "thirdparty/Lua/lua-5.4.3/src/lua.o" \



DIR_INCLUDES +=  \
-I"../" \
-I"../grid" \
-I"../usb/class/midi/" \
-I"../usb/class/midi/device" \
-I"../thirdparty/Lua/lua-5.4.3/src" \



DEPS_AS_ARGS +=  \
\
"usb/class/midi/device/audiodf_midi.d" \
"usb/class/midi/usb_protocol_midi.d" \
"grid/grid_ain.d" \
"grid/grid_buf.d" \
"grid/grid_d51.d" \
"grid/grid_debug.d" \
"grid/grid_default.d" \
"grid/grid_expr.d" \
"grid/grid_hardwaretest.d" \
"grid/grid_led.d" \
"grid/grid_module.d" \
"grid/grid_module_bu16.d" \
"grid/grid_module_en16.d" \
"grid/grid_module_pbf4.d" \
"grid/grid_module_po16.d" \
"grid/grid_module_ef44.d" \
"grid/grid_msg.d" \
"grid/grid_nvm.d" \
"grid/grid_protocol.d" \
"grid/grid_sys.d" \
"grid/grid_ui.d" \
"grid/grid_unittest.d" \
"grid/grid_usb.d" \
"grid/grid_lua_api.d" \
"thirdparty/Lua/lua-5.4.3/src/lapi.d" \
"thirdparty/Lua/lua-5.4.3/src/lctype.d" \
"thirdparty/Lua/lua-5.4.3/src/lfunc.d" \
"thirdparty/Lua/lua-5.4.3/src/lmathlib.d" \
"thirdparty/Lua/lua-5.4.3/src/loslib.d" \
"thirdparty/Lua/lua-5.4.3/src/ltable.d" \
"thirdparty/Lua/lua-5.4.3/src/lundump.d" \
"thirdparty/Lua/lua-5.4.3/src/lauxlib.d" \
"thirdparty/Lua/lua-5.4.3/src/ldblib.d" \
"thirdparty/Lua/lua-5.4.3/src/lgc.d" \
"thirdparty/Lua/lua-5.4.3/src/lmem.d" \
"thirdparty/Lua/lua-5.4.3/src/lparser.d" \
"thirdparty/Lua/lua-5.4.3/src/ltablib.d" \
"thirdparty/Lua/lua-5.4.3/src/lutf8lib.d" \
"thirdparty/Lua/lua-5.4.3/src/lbaselib.d" \
"thirdparty/Lua/lua-5.4.3/src/ldebug.d" \
"thirdparty/Lua/lua-5.4.3/src/linit.d" \
"thirdparty/Lua/lua-5.4.3/src/loadlib.d" \
"thirdparty/Lua/lua-5.4.3/src/lstate.d" \
"thirdparty/Lua/lua-5.4.3/src/ltm.d" \
"thirdparty/Lua/lua-5.4.3/src/lvm.d" \
"thirdparty/Lua/lua-5.4.3/src/lcode.d" \
"thirdparty/Lua/lua-5.4.3/src/ldo.d" \
"thirdparty/Lua/lua-5.4.3/src/liolib.d" \
"thirdparty/Lua/lua-5.4.3/src/lobject.d" \
"thirdparty/Lua/lua-5.4.3/src/lstring.d" \
"thirdparty/Lua/lua-5.4.3/src/lzio.d" \
"thirdparty/Lua/lua-5.4.3/src/llex.d" \
"thirdparty/Lua/lua-5.4.3/src/lopcodes.d" \
"thirdparty/Lua/lua-5.4.3/src/ldump.d" \
"thirdparty/Lua/lua-5.4.3/src/lstrlib.d" \
"thirdparty/Lua/lua-5.4.3/src/lcorolib.d" \

# "thirdparty/Lua/lua-5.4.3/src/luac.d" \
# "thirdparty/Lua/lua-5.4.3/src/lua.d" \

################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ifdef SystemRoot
	SHELL = cmd.exe
	MK_DIR = mkdir
else
	ifeq ($(shell uname), Linux)
		MK_DIR = mkdir -p
	endif

	ifeq ($(shell uname | cut -d _ -f 1), CYGWIN)
		MK_DIR = mkdir -p
	endif

	ifeq ($(shell uname | cut -d _ -f 1), MINGW32)
		MK_DIR = mkdir -p
	endif

	ifeq ($(shell uname | cut -d _ -f 1), MINGW64)
		MK_DIR = mkdir -p
	endif

	ifeq ($(shell uname | cut -d _ -f 1), DARWIN)
		MK_DIR = mkdir -p
	endif
endif

# List the subdirectories for creating object files
SUB_DIRS +=  \
 \
hpl/adc \
usb/class/cdc/device \
hpl/ramecc \
samd51a/gcc/gcc \
hpl/evsys \
hpl/qspi \
examples \
hpl/systick \
hpl/oscctrl \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0 \
stdio_redirect \
hpl/tc \
hpl/osc32kctrl \
usb \
hpl/dmac \
hal/src \
stdio_redirect/gcc \
samd51a/gcc \
hal/utils/src \
hpl/wdt \
hpl/rtc \
hpl/trng \
usb/class/hid/device \
hpl/usb \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/portable/GCC/ARM_CM4F \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/portable/MemMang \
hpl/mclk \
hpl/cmcc \
hpl/gclk \
usb/device \
hpl/pm \
usb/class/msc/device \
hpl/pac \
hpl/sercom \
hpl/core \
hpl/nvmctrl \
hpl/dsu

# List the object files
OBJS +=  \
hal/src/hal_io.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/list.o \
hpl/pac/hpl_pac.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/portable/GCC/ARM_CM4F/port.o \
hal/src/hal_i2c_m_async.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/event_groups.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/portable/MemMang/heap_4.o \
hpl/wdt/hpl_wdt.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/croutine.o \
usb/usb_protocol.o \
stdio_redirect/stdio_io.o \
hal/src/hal_spi_m_dma.o \
stdio_redirect/gcc/write.o \
samd51a/gcc/system_samd51.o \
usb/class/hid/device/hiddf_generic.o \
hal/src/hal_init.o \
hpl/evsys/hpl_evsys.o \
hpl/core/hpl_core_m4.o \
hal/src/hal_cache.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/stream_buffer.o \
usb/class/cdc/device/cdcdf_acm.o \
hal/utils/src/utils_syscalls.o \
hpl/qspi/hpl_qspi.o \
hpl/nvmctrl/hpl_nvmctrl.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/queue.o \
usb_start.o \
hal/src/hal_timer.o \
hpl/usb/hpl_usb.o \
stdio_redirect/gcc/read.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/timers.o \
hal/src/hal_delay.o \
hpl/pm/hpl_pm.o \
hpl/core/hpl_init.o \
hpl/ramecc/hpl_ramecc.o \
hal/src/hal_wdt.o \
usb/class/hid/device/hiddf_mouse.o \
hal/utils/src/utils_assert.o \
hpl/dmac/hpl_dmac.o \
hal/src/hal_adc_async.o \
hpl/oscctrl/hpl_oscctrl.o \
hal/src/hal_rand_sync.o \
hpl/trng/hpl_trng.o \
usb/class/hid/device/hiddf_keyboard.o \
hal/src/hal_usart_sync.o \
hpl/mclk/hpl_mclk.o \
hpl/gclk/hpl_gclk.o \
stdio_start.o \
hal/src/hal_flash.o \
hal/src/hal_spi_m_async.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/rtos_port.o \
hal/src/hal_crc_sync.o \
hal/src/hal_usb_device.o \
rtos_start.o \
hal/utils/src/utils_list.o \
hpl/osc32kctrl/hpl_osc32kctrl.o \
hpl/rtc/hpl_rtc.o \
examples/driver_examples.o \
driver_init.o \
hal/src/hal_usart_async.o \
usb/class/msc/device/mscdf.o \
hpl/sercom/hpl_sercom.o \
hal/utils/src/utils_ringbuffer.o \
hal/src/hal_atomic.o \
main.o \
hal/src/hal_gpio.o \
hal/src/hal_qspi_dma.o \
thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/tasks.o \
hal/src/hal_evsys.o \
hal/utils/src/utils_event.o \
hal/src/hal_sleep.o \
hpl/adc/hpl_adc.o \
samd51a/gcc/gcc/startup_samd51.o \
atmel_start.o \
usb/device/usbdc.o \
hpl/tc/hpl_tc.o \
hpl/cmcc/hpl_cmcc.o \
hpl/systick/hpl_systick.o \
hpl/dsu/hpl_dsu.o

OBJS_AS_ARGS +=  \
"hal/src/hal_io.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/list.o" \
"hpl/pac/hpl_pac.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/portable/GCC/ARM_CM4F/port.o" \
"hal/src/hal_i2c_m_async.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/event_groups.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/portable/MemMang/heap_4.o" \
"hpl/wdt/hpl_wdt.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/croutine.o" \
"usb/usb_protocol.o" \
"stdio_redirect/stdio_io.o" \
"hal/src/hal_spi_m_dma.o" \
"stdio_redirect/gcc/write.o" \
"samd51a/gcc/system_samd51.o" \
"usb/class/hid/device/hiddf_generic.o" \
"hal/src/hal_init.o" \
"hpl/evsys/hpl_evsys.o" \
"hpl/core/hpl_core_m4.o" \
"hal/src/hal_cache.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/stream_buffer.o" \
"usb/class/cdc/device/cdcdf_acm.o" \
"hal/utils/src/utils_syscalls.o" \
"hpl/qspi/hpl_qspi.o" \
"hpl/nvmctrl/hpl_nvmctrl.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/queue.o" \
"usb_start.o" \
"hal/src/hal_timer.o" \
"hpl/usb/hpl_usb.o" \
"stdio_redirect/gcc/read.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/timers.o" \
"hal/src/hal_delay.o" \
"hpl/pm/hpl_pm.o" \
"hpl/core/hpl_init.o" \
"hpl/ramecc/hpl_ramecc.o" \
"hal/src/hal_wdt.o" \
"usb/class/hid/device/hiddf_mouse.o" \
"hal/utils/src/utils_assert.o" \
"hpl/dmac/hpl_dmac.o" \
"hal/src/hal_adc_async.o" \
"hpl/oscctrl/hpl_oscctrl.o" \
"hal/src/hal_rand_sync.o" \
"hpl/trng/hpl_trng.o" \
"usb/class/hid/device/hiddf_keyboard.o" \
"hal/src/hal_usart_sync.o" \
"hpl/mclk/hpl_mclk.o" \
"hpl/gclk/hpl_gclk.o" \
"stdio_start.o" \
"hal/src/hal_flash.o" \
"hal/src/hal_spi_m_async.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/rtos_port.o" \
"hal/src/hal_crc_sync.o" \
"hal/src/hal_usb_device.o" \
"rtos_start.o" \
"hal/utils/src/utils_list.o" \
"hpl/osc32kctrl/hpl_osc32kctrl.o" \
"hpl/rtc/hpl_rtc.o" \
"examples/driver_examples.o" \
"driver_init.o" \
"hal/src/hal_usart_async.o" \
"usb/class/msc/device/mscdf.o" \
"hpl/sercom/hpl_sercom.o" \
"hal/utils/src/utils_ringbuffer.o" \
"hal/src/hal_atomic.o" \
"main.o" \
"hal/src/hal_gpio.o" \
"hal/src/hal_qspi_dma.o" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/tasks.o" \
"hal/src/hal_evsys.o" \
"hal/utils/src/utils_event.o" \
"hal/src/hal_sleep.o" \
"hpl/adc/hpl_adc.o" \
"samd51a/gcc/gcc/startup_samd51.o" \
"atmel_start.o" \
"usb/device/usbdc.o" \
"hpl/tc/hpl_tc.o" \
"hpl/cmcc/hpl_cmcc.o" \
"hpl/systick/hpl_systick.o" \
"hpl/dsu/hpl_dsu.o"

# List the directories containing header files
DIR_INCLUDES +=  \
-I"../" \
-I"../config" \
-I"../examples" \
-I"../hal/include" \
-I"../hal/utils/include" \
-I"../hpl/adc" \
-I"../hpl/cmcc" \
-I"../hpl/core" \
-I"../hpl/dmac" \
-I"../hpl/dsu" \
-I"../hpl/evsys" \
-I"../hpl/gclk" \
-I"../hpl/mclk" \
-I"../hpl/nvmctrl" \
-I"../hpl/osc32kctrl" \
-I"../hpl/oscctrl" \
-I"../hpl/pac" \
-I"../hpl/pm" \
-I"../hpl/port" \
-I"../hpl/qspi" \
-I"../hpl/ramecc" \
-I"../hpl/rtc" \
-I"../hpl/sercom" \
-I"../hpl/systick" \
-I"../hpl/tc" \
-I"../hpl/trng" \
-I"../hpl/usb" \
-I"../hpl/wdt" \
-I"../hri" \
-I"../" \
-I"../config" \
-I"../thirdparty/RTOS" \
-I"../thirdparty/RTOS/freertos/FreeRTOSV10.0.0" \
-I"../thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/include" \
-I"../thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/portable/GCC/ARM_CM4F" \
-I"../thirdparty/RTOS/freertos/FreeRTOSV10.0.0/module_config" \
-I"../" \
-I"../config" \
-I"../usb" \
-I"../usb/class/cdc" \
-I"../usb/class/cdc/device" \
-I"../usb/class/composite/device" \
-I"../usb/class/hid" \
-I"../usb/class/hid/device" \
-I"../usb/class/hub" \
-I"../usb/class/msc" \
-I"../usb/class/msc/device" \
-I"../usb/class/vendor" \
-I"../usb/device" \
-I"../" \
-I"../config" \
-I"../stdio_redirect" \
-I"../" \
-I"../CMSIS/Core/Include" \
-I"../samd51a/include"

# List the dependency files
DEPS := $(OBJS:%.o=%.d)

DEPS_AS_ARGS +=  \
"usb/usb_protocol.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/event_groups.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/croutine.d" \
"hpl/wdt/hpl_wdt.d" \
"stdio_redirect/stdio_io.d" \
"hal/utils/src/utils_event.d" \
"hal/src/hal_io.d" \
"hpl/ramecc/hpl_ramecc.d" \
"hpl/qspi/hpl_qspi.d" \
"hpl/core/hpl_core_m4.d" \
"hpl/evsys/hpl_evsys.d" \
"hal/utils/src/utils_syscalls.d" \
"usb/class/cdc/device/cdcdf_acm.d" \
"samd51a/gcc/system_samd51.d" \
"stdio_redirect/gcc/write.d" \
"hal/src/hal_spi_m_dma.d" \
"hpl/usb/hpl_usb.d" \
"main.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/timers.d" \
"stdio_redirect/gcc/read.d" \
"usb/class/msc/device/mscdf.d" \
"hpl/nvmctrl/hpl_nvmctrl.d" \
"hal/src/hal_init.d" \
"hal/src/hal_timer.d" \
"usb/class/hid/device/hiddf_mouse.d" \
"hal/src/hal_wdt.d" \
"hpl/cmcc/hpl_cmcc.d" \
"hal/src/hal_adc_async.d" \
"hpl/dmac/hpl_dmac.d" \
"hal/utils/src/utils_assert.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/stream_buffer.d" \
"hal/src/hal_delay.d" \
"hal/src/hal_crc_sync.d" \
"hpl/core/hpl_init.d" \
"hpl/pm/hpl_pm.d" \
"hal/src/hal_flash.d" \
"stdio_start.d" \
"hpl/gclk/hpl_gclk.d" \
"hal/src/hal_usb_device.d" \
"hpl/pac/hpl_pac.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/rtos_port.d" \
"hal/src/hal_spi_m_async.d" \
"hal/src/hal_usart_sync.d" \
"usb/class/hid/device/hiddf_keyboard.d" \
"hpl/trng/hpl_trng.d" \
"hal/src/hal_rand_sync.d" \
"hpl/mclk/hpl_mclk.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/portable/GCC/ARM_CM4F/port.d" \
"driver_init.d" \
"usb_start.d" \
"hpl/systick/hpl_systick.d" \
"hal/src/hal_usart_async.d" \
"hpl/osc32kctrl/hpl_osc32kctrl.d" \
"rtos_start.d" \
"examples/driver_examples.d" \
"hpl/rtc/hpl_rtc.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/portable/MemMang/heap_4.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/list.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/queue.d" \
"hal/src/hal_qspi_dma.d" \
"hal/src/hal_cache.d" \
"hal/utils/src/utils_list.d" \
"hal/src/hal_sleep.d" \
"hal/utils/src/utils_ringbuffer.d" \
"hpl/sercom/hpl_sercom.d" \
"hal/src/hal_evsys.d" \
"hal/src/hal_gpio.d" \
"usb/class/hid/device/hiddf_generic.d" \
"hal/src/hal_i2c_m_async.d" \
"hal/src/hal_atomic.d" \
"hpl/dsu/hpl_dsu.d" \
"hpl/tc/hpl_tc.d" \
"usb/device/usbdc.d" \
"hpl/oscctrl/hpl_oscctrl.d" \
"hpl/adc/hpl_adc.d" \
"thirdparty/RTOS/freertos/FreeRTOSV10.0.0/Source/tasks.d" \
"samd51a/gcc/gcc/startup_samd51.d" \
"atmel_start.d"

OUTPUT_FILE_NAME :=AtmelStart
QUOTE := "
OUTPUT_FILE_PATH +=$(OUTPUT_FILE_NAME).elf
OUTPUT_FILE_PATH_AS_ARGS +=$(OUTPUT_FILE_NAME).elf

vpath %.c ../
vpath %.s ../
vpath %.S ../

# All Target
all: $(SUB_DIRS) $(OUTPUT_FILE_PATH)

# Linker target

$(OUTPUT_FILE_PATH): $(OBJS)
	@echo Building target: $@
	@echo Invoking: ARM/GNU Linker
	$(QUOTE)arm-none-eabi-gcc$(QUOTE) -o $(OUTPUT_FILE_NAME).elf $(OBJS_AS_ARGS) -Wl,--start-group -lm -Wl,--end-group -mthumb \
-Wl,-Map="$(OUTPUT_FILE_NAME).map" --specs=nano.specs -Wl,--gc-sections -mcpu=cortex-m4 -u _printf_float\
 \
-T"../grid/samd51n20a_flash_bootloader.ld" \
-L"../samd51a/gcc/gcc" \

	@echo Finished building target: $@

	"arm-none-eabi-objcopy" -O binary "$(OUTPUT_FILE_NAME).elf" "$(OUTPUT_FILE_NAME).bin"
	"arm-none-eabi-objcopy" -O ihex -R .eeprom -R .fuse -R .lock -R .signature  \
        "$(OUTPUT_FILE_NAME).elf" "$(OUTPUT_FILE_NAME).hex"
	"arm-none-eabi-objcopy" -j .eeprom --set-section-flags=.eeprom=alloc,load --change-section-lma \
        .eeprom=0 --no-change-warnings -O binary "$(OUTPUT_FILE_NAME).elf" \
        "$(OUTPUT_FILE_NAME).eep" || exit 0
	"arm-none-eabi-objdump" -h -S "$(OUTPUT_FILE_NAME).elf" > "$(OUTPUT_FILE_NAME).lss"
	"arm-none-eabi-size" "$(OUTPUT_FILE_NAME).elf"

	

# Compiler targets




%.o: %.c
	@echo Building file: $<
	@echo ARM/GNU C Compiler
	$(QUOTE)arm-none-eabi-gcc$(QUOTE) -x c -mthumb $(GRID_DEFINES) -DDEBUG -Os -ffunction-sections -mlong-calls -g3 -Wall -c -std=gnu99 \
-D__SAMD51N20A__ -mcpu=cortex-m4 -mfloat-abi=softfp -mfpu=fpv4-sp-d16 \
$(DIR_INCLUDES) \
-MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"  -o "$@" "$<"
	@echo Finished building: $<

%.o: %.s
	@echo Building file: $<
	@echo ARM/GNU Assembler
	$(QUOTE)arm-none-eabi-as$(QUOTE) -x c -mthumb $(GRID_DEFINES) -DDEBUG -Os -ffunction-sections -mlong-calls -g3 -Wall -c -std=gnu99 \
-D__SAMD51N20A__ -mcpu=cortex-m4 -mfloat-abi=softfp -mfpu=fpv4-sp-d16 \
$(DIR_INCLUDES) \
-MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"  -o "$@" "$<"
	@echo Finished building: $<

%.o: %.S
	@echo Building file: $<
	@echo ARM/GNU Preprocessing Assembler
	$(QUOTE)arm-none-eabi-gcc$(QUOTE) -x c -mthumb $(GRID_DEFINES) -DDEBUG -Os -ffunction-sections -mlong-calls -g3 -Wall -c -std=gnu99 \
-D__SAMD51N20A__ -mcpu=cortex-m4 -mfloat-abi=softfp -mfpu=fpv4-sp-d16 \
$(DIR_INCLUDES) \
-MD -MP -MF "$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)"  -o "$@" "$<"
	@echo Finished building: $<

# Detect changes in the dependent files and recompile the respective object files.
ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(DEPS)),)
-include $(DEPS)
endif
endif


$(SUB_DIRS):
	$(MK_DIR) "$@"

clean:
	rm -f lastconfig.txt
	rm -f $(OBJS_AS_ARGS)
	rm -f $(OUTPUT_FILE_PATH)
	rm -f $(DEPS_AS_ARGS)
	rm -f $(OUTPUT_FILE_NAME).a $(OUTPUT_FILE_NAME).hex $(OUTPUT_FILE_NAME).bin \
        $(OUTPUT_FILE_NAME).lss $(OUTPUT_FILE_NAME).eep $(OUTPUT_FILE_NAME).map \
        $(OUTPUT_FILE_NAME).srec

# ================== NIGHTLY WITH AUTOUPLOAD =================
nightly: GRID_DEFINES = -DGRID_BUILD_NIGHTLY
ifneq (nightly, $(file < lastconfig.txt))
nightly: clean $(SUB_DIRS) $(OUTPUT_FILE_PATH) nightly_post
else
nightly: $(SUB_DIRS) $(OUTPUT_FILE_PATH) nightly_post
endif
nightly_post: 
	@echo "nightly" > lastconfig.txt
	python3 ./../buildscripts/uf2conv.py -c -b 0x4000 -o ./../../binary/grid_nightly.uf2 ./AtmelStart.bin
	cp ./../../binary/grid_nightly.uf2 /media/${shell whoami}/GRID

# ================== DEBUG WITH AUTOGDB =================
debug: GRID_DEFINES = -DGRID_BUILD_DEBUG
ifneq (debug, $(file < lastconfig.txt))
debug: clean $(SUB_DIRS) $(OUTPUT_FILE_PATH) debug_post
else
debug: $(SUB_DIRS) $(OUTPUT_FILE_PATH) debug_post
endif
debug_post: 
	@echo "debug" > lastconfig.txt
	arm-none-eabi-gdb -iex "target extended-remote localhost:3333" AtmelStart.elf

# ================== RELEASE =================
release: GRID_DEFINES = -DGRID_BUILD_RELEASE
ifneq (release, $(file < lastconfig.txt))
release: clean $(SUB_DIRS) $(OUTPUT_FILE_PATH) release_post
else
release: $(SUB_DIRS) $(OUTPUT_FILE_PATH) release_post
endif
release_post:
	@echo "release" > lastconfig.txt
	python3 ./../buildscripts/uf2conv.py -c -b 0x4000 -o ./../../binary/grid_release.uf2 ./AtmelStart.bin

# ================== NIGHTLY FOR AUTOMATION =================
nightly_automation: GRID_DEFINES = -DGRID_BUILD_NIGHTLY
nightly_automation: clean $(SUB_DIRS) $(OUTPUT_FILE_PATH) nightly_automation_post
nightly_automation_post: 
	python3 ./../buildscripts/uf2conv.py -c -b 0x4000 -o ./../../binary/grid_nightly.uf2 ./AtmelStart.bin

# ================== RELEASE FOR AUTOMATION =================
release_automation: GRID_DEFINES = -DGRID_BUILD_RELEASE
release_automation: clean $(SUB_DIRS) $(OUTPUT_FILE_PATH) release_automation_post
release_automation_post:
	python3 ./../buildscripts/uf2conv.py -c -b 0x4000 -o ./../../binary/grid_release.uf2 ./AtmelStart.bin
