#ifndef GRID_PROTOCOL_H_INCLUDED
#define GRID_PROTOCOL_H_INCLUDED

#define GRID_PROTOCOL_VERSION_MAJOR		1
#define GRID_PROTOCOL_VERSION_MINOR		0
#define GRID_PROTOCOL_VERSION_PATCH		4


// Module HWCFG definitions

#define  GRID_MODULE_PO16_RevB		0
#define  GRID_MODULE_PO16_RevC		8

#define  GRID_MODULE_BU16_RevB		128
#define  GRID_MODULE_BU16_RevC		136

#define  GRID_MODULE_PBF4_RevA		64
#define  GRID_MODULE_EN16_RevA		192

#define  GRID_PARAMETER_SYS_HEARTBEAT_INTERVAL	250
#define  GRID_PARAMETER_SYS_PING_INTERVAL		100



#define GRID_CONST_NUL				0x00

#define GRID_CONST_SOH				0x01	//start of header
#define GRID_CONST_STX				0x02	//start of text
#define GRID_CONST_ETX				0x03	//end of text
#define GRID_CONST_EOB				0x17	//end of block
#define GRID_CONST_EOT				0x04	//end of transmission

#define GRID_CONST_LF				0x0A	//linefeed, newline

#define GRID_CONST_ACK				0x06	//acknowledge
#define GRID_CONST_NAK				0x15	//nacknowledge	
#define GRID_CONST_CAN				0x18	//cancel

#define GRID_CONST_NORTH			0x11	// Device Control 1
#define GRID_CONST_EAST				0x12	// Device Control 2
#define GRID_CONST_SOUTH			0x13	// Device Control 3
#define GRID_CONST_WEST				0x14	// Device Control 4

#define GRID_CONST_DCT				0x0E	// Shift In = Direct
#define GRID_CONST_BRC				0x0F	// Shift Out = Broadcast

#define GRID_CONST_BELL				0x07 	


#define GRID_PARAMETER_GET			0
#define GRID_PARAMETER_SET			1


#define GRID_CLASS_MIDI										0
#define GRID_COMMAND_MIDI_EVENTPACKET						100

#define GRID_PARAMETER_MIDI_NOTEOFF							0x80
#define GRID_PARAMETER_MIDI_NOTEON							0x90
#define GRID_PARAMETER_MIDI_CONTROLCHANGE					176

#define GRID_CLASS_KEYBOARD									1
#define GRID_COMMAND_KEYBOARD_KEYDOWN						128
#define GRID_COMMAND_KEYBOARD_KEYUP							129
#define GRID_PARAMETER_KEYBOARD_MODIFIER					130
#define GRID_PARAMETER_KEYBOARD_NOTMODIFIER					131
	
#define GRID_CLASS_MOUSE									2

#define GRID_CLASS_LED										3
#define GRID_COMMAND_LED_SETPHASE							99
#define GRID_COMMAND_LED_SETCOLOR							100
	
#define GRID_CLASS_SYS										4
#define GRID_CONTEXT_SYS_BANK								100

#define GRID_COMMAND_SYS_HEARTBEAT							102
#define GRID_PARAMETER_SYS_HEARTBEAT_ALIVE					103

#define GRID_COMMAND_SYS_CFG								104
#define GRID_PARAMETER_SYS_CFG_REQUEST						105



#define GRID_CLASS_DEBUG									5
#define GRID_COMMAND_DEBUG_TEXT								106
#define GRID_COMMAND_DEBUG_RAW								107



// HEADER BROADCAST

#define GRID_SOH_BRC_FORMAT							"%c%c............%02x%02x%02x%c"
#define GRID_SOH_BRC_PARAMETERS						GRID_CONST_SOH,GRID_CONST_BRC,GRID_PROTOCOL_VERSION_MAJOR,GRID_PROTOCOL_VERSION_MINOR,GRID_PROTOCOL_VERSION_PATCH,GRID_CONST_EOB


#define GRID_SOH_BRC_PARAMETER_OFFSET_LEN			2
#define GRID_SOH_BRC_PARAMETER_LENGTH_LEN			2

#define GRID_SOH_BRC_PARAMETER_OFFSET_ID			4
#define GRID_SOH_BRC_PARAMETER_LENGTH_ID			2

#define GRID_SOH_BRC_PARAMETER_OFFSET_DX			6
#define GRID_SOH_BRC_PARAMETER_LENGTH_DX			2

#define GRID_SOH_BRC_PARAMETER_OFFSET_DY			8
#define GRID_SOH_BRC_PARAMETER_LENGTH_DY			2

#define GRID_SOH_BRC_PARAMETER_OFFSET_AGE			10
#define GRID_SOH_BRC_PARAMETER_LENGTH_AGE			2

#define GRID_SOH_BRC_PARAMETER_OFFSET_ROT			12
#define GRID_SOH_BRC_PARAMETER_LENGTH_ROT			2

#define GRID_SOH_BRC_PARAMETER_OFFSET_VMAJOR		14
#define GRID_SOH_BRC_PARAMETER_LENGTH_VMAJOR		2

#define GRID_SOH_BRC_PARAMETER_OFFSET_VMINOR		16
#define GRID_SOH_BRC_PARAMETER_LENGTH_VMINOR		2

#define GRID_SOH_BRC_PARAMETER_OFFSET_VPATCH		18
#define GRID_SOH_BRC_PARAMETER_LENGTH_VPATCH		2


// STX SYS HEARTBEAT

#define GRID_STX_SYS_HEARTBEAT_FORMAT					"%c%02x%02x..%c"
#define GRID_STX_SYS_HEARTBEAT_PARAMETERS				GRID_CONST_STX,GRID_CLASS_SYS,GRID_COMMAND_SYS_HEARTBEAT,GRID_CONST_ETX

#define GRID_STX_SYS_HEARTBEAT_PARAMETER_OFFSET_HWCFG	5
#define GRID_STX_SYS_HEARTBEAT_PARAMETER_LENGTH_HWCFG	2

// STX SYS CFG

#define GRID_STX_SYS_CFG_FORMAT						"%c%02x%02x......%c"
#define GRID_STX_SYS_CFG_PARAMETERS					GRID_CONST_STX,GRID_CLASS_SYS,GRID_COMMAND_SYS_CFG,GRID_CONST_ETX

#define GRID_STX_SYS_CFG_PARAMETER_OFFSET_CFGCONTEXT	5
#define GRID_STX_SYS_CFG_PARAMETER_LENGTH_CFGCONTEXT	2

#define GRID_STX_SYS_CFG_PARAMETER_OFFSET_CFGCOMMAND	7
#define GRID_STX_SYS_CFG_PARAMETER_LENGTH_CFGCOMMAND	2

#define GRID_STX_SYS_CFG_PARAMETER_OFFSET_CFGPARAM1		9
#define GRID_STX_SYS_CFG_PARAMETER_LENGTH_CFGPARAM1		2


// STX MIDI EVENTPACKET

#define GRID_STX_MIDI_EVENTPACKET_FORMAT			"%c%02x%02x........%c"
#define GRID_STX_MIDI_EVENTPACKET_PARAMETERS		GRID_CONST_STX,GRID_CLASS_MIDI,GRID_COMMAND_MIDI_EVENTPACKET,GRID_CONST_ETX

#define GRID_STX_MIDI_EVENTPACKET_PARAMETER_OFFSET_CABLECHANNEL	5
#define GRID_STX_MIDI_EVENTPACKET_PARAMETER_LENGTH_CABLECHANNEL	2

#define GRID_STX_MIDI_EVENTPACKET_PARAMETER_OFFSET_MIDICOMMAND	7
#define GRID_STX_MIDI_EVENTPACKET_PARAMETER_LENGTH_MIDICOMMAND	2

#define GRID_STX_MIDI_EVENTPACKET_PARAMETER_OFFSET_MIDIPARAM1	9
#define GRID_STX_MIDI_EVENTPACKET_PARAMETER_LENGTH_MIDIPARAM1	2

#define GRID_STX_MIDI_EVENTPACKET_PARAMETER_OFFSET_MIDIPARAM2	11
#define GRID_STX_MIDI_EVENTPACKET_PARAMETER_LENGTH_MIDIPARAM2	2



#define GRID_STX_DEBUG_TEXT_FORMAT			"%c%02x%02x"
#define GRID_STX_DEBUG_TEXT_PARAMETERS		GRID_CONST_STX,GRID_CLASS_DEBUG,GRID_COMMAND_DEBUG_TEXT

#define GRID_STX_DEBUG_TEXT_PARAMETER_OFFSET_TEXTLENGTH	5
#define GRID_STX_DEBUG_TEXT_PARAMETER_LENGTH_TEXTLENGTH	2

#define GRID_STX_DEBUG_TEXT_PARAMETER_OFFSET_TEXTDATA	7
#define GRID_STX_DEBUG_TEXT_PARAMETER_LENGTH_TEXTDATA	2

#define GRID_STX_DEBUG_TEXT_MEXLENGTH 100



#endif /* GRID_PROTOCOL_H_INCLUDED */