#ifndef GRID_PROTOCOL_H_INCLUDED
#define GRID_PROTOCOL_H_INCLUDED

#define GRID_PROTOCOL_VERSION_MAJOR		1
#define GRID_PROTOCOL_VERSION_MINOR		1
#define GRID_PROTOCOL_VERSION_PATCH		3


// Module HWCFG definitions

#define  GRID_MODULE_PO16_RevB		0
#define  GRID_MODULE_PO16_RevC		8

#define  GRID_MODULE_BU16_RevB		128
#define  GRID_MODULE_BU16_RevC		136

#define  GRID_MODULE_PBF4_RevA		64
#define  GRID_MODULE_EN16_RevA		192

#define  GRID_PARAMETER_HEARTBEAT_interval	250
#define  GRID_PARAMETER_PING_interval		100

#define  GRID_PARAMETER_TEXT_maxlength		150
#define  GRID_PARAMETER_PACKET_maxlength	400
#define  GRID_PARAMETER_PACKET_marign		200


// SPECIAL CHARACTERS

#define GRID_CONST_NUL				0x00

#define GRID_CONST_SOH				0x01	//start of header
#define GRID_CONST_STX				0x02	//start of text
#define GRID_CONST_ETX				0x03	//end of text
#define GRID_CONST_EOB				0x17	//end of block
#define GRID_CONST_EOT				0x04	//end of transmission

#define GRID_CONST_LF				0x0A	//linefeed, newline

#define GRID_CONST_ACK				0x06	//acknowledge
#define GRID_CONST_NAK				0x15	//nacknowledge	
#define GRID_CONST_CAN				0x18	//cancel

#define GRID_CONST_NORTH			0x11	// Device Control 1
#define GRID_CONST_EAST				0x12	// Device Control 2
#define GRID_CONST_SOUTH			0x13	// Device Control 3
#define GRID_CONST_WEST				0x14	// Device Control 4

#define GRID_CONST_DCT				0x0E	// Shift In = Direct
#define GRID_CONST_BRC				0x0F	// Shift Out = Broadcast

#define GRID_CONST_BELL				0x07 	





#define GRID_PARAMETER_MIDI_NOTEOFF							0x80
#define GRID_PARAMETER_MIDI_NOTEON							0x90
#define GRID_PARAMETER_MIDI_CONTROLCHANGE					0xB0


#define GRID_PARAMETER_KEYBOARD_KEYDOWN						128
#define GRID_PARAMETER_KEYBOARD_KEYUP						129
#define GRID_PARAMETER_KEYBOARD_MODIFIER					130
#define GRID_PARAMETER_KEYBOARD_NOTMODIFIER					131
 	



// HEADER BROADCAST

#define GRID_BRC_frame				"%c%c............%c",GRID_CONST_SOH,GRID_CONST_BRC,GRID_CONST_EOB


#define GRID_BRC_LEN_offset			2
#define GRID_BRC_LEN_length			2

#define GRID_BRC_ID_offset			4
#define GRID_BRC_ID_length			2

#define GRID_BRC_DX_offset			6
#define GRID_BRC_DX_length			2

#define GRID_BRC_DY_offset			8
#define GRID_BRC_DY_length			2

#define GRID_BRC_AGE_offset			10
#define GRID_BRC_AGE_length			2

#define GRID_BRC_ROT_offset			12
#define GRID_BRC_ROT_length			2


//NEW ERA


#define GRID_INSTR_length					1
#define GRID_INSTR_offset					4


// Save the following action to the given event & change instruction to execute
#define GRID_INSTR_ACKNOWLEDGE_code			0xA//a

#define GRID_INSTR_NACKNOWLEDGE_code		0xB//b



#define GRID_INSTR_CONFIGURE_code			0xC//c

#define GRID_INSTR_REPORT_code				0xD//c

// Respond with executable please!
#define GRID_INSTR_FETCH_code				0xF//e

// Execute The Action if possible!
#define GRID_INSTR_EXECUTE_code				0xE//f


#define GRID_CLASS_length					3
#define GRID_CLASS_offset					1

// ================== MIDI RELATIVE CLASS =================== //
#define GRID_CLASS_MIDIRELATIVE_code		0x000
#define GRID_CLASS_MIDIRELATIVE_frame		"%c%03x_........%c",GRID_CONST_STX,GRID_CLASS_MIDIRELATIVE_code,GRID_CONST_ETX

#define GRID_CLASS_MIDIRELATIVE_CABLECOMMAND_offset			5
#define GRID_CLASS_MIDIRELATIVE_CABLECOMMAND_length			2

#define GRID_CLASS_MIDIRELATIVE_COMMANDCHANNEL_offset		7
#define GRID_CLASS_MIDIRELATIVE_COMMANDCHANNEL_length		2

#define GRID_CLASS_MIDIRELATIVE_PARAM1_offset				9
#define GRID_CLASS_MIDIRELATIVE_PARAM1_length				2

#define GRID_CLASS_MIDIRELATIVE_PARAM2_offset				11
#define GRID_CLASS_MIDIRELATIVE_PARAM2_length				2


// ================== MIDI ABSOLUTE CLASS =================== //
#define GRID_CLASS_MIDIABSOLUTE_code		0x001
#define GRID_CLASS_MIDIABSOLUTE_frame		"%c%03x_........%c",GRID_CONST_STX,GRID_CLASS_MIDIABSOLUTE_code,GRID_CONST_ETX

#define GRID_CLASS_MIDIABSOLUTE_CABLECOMMAND_offset			5
#define GRID_CLASS_MIDIABSOLUTE_CABLECOMMAND_length			2

#define GRID_CLASS_MIDIABSOLUTE_COMMANDCHANNEL_offset		7
#define GRID_CLASS_MIDIABSOLUTE_COMMANDCHANNEL_length		2

#define GRID_CLASS_MIDIABSOLUTE_PARAM1_offset				9
#define GRID_CLASS_MIDIABSOLUTE_PARAM1_length				2

#define GRID_CLASS_MIDIABSOLUTE_PARAM2_offset				11
#define GRID_CLASS_MIDIABSOLUTE_PARAM2_length				2


// HEARTBEAT
#define GRID_CLASS_HEARTBEAT_code				0x010
#define GRID_CLASS_HEARTBEAT_frame				"%c%03x_........%c",GRID_CONST_STX,GRID_CLASS_HEARTBEAT_code,GRID_CONST_ETX

#define GRID_CLASS_HEARTBEAT_HWCFG_offset		5
#define GRID_CLASS_HEARTBEAT_HWCFG_length		2

#define GRID_CLASS_HEARTBEAT_VMAJOR_offset		7
#define GRID_CLASS_HEARTBEAT_VMAJOR_length		2

#define GRID_CLASS_HEARTBEAT_VMINOR_offset		9
#define GRID_CLASS_HEARTBEAT_VMINOR_length		2

#define GRID_CLASS_HEARTBEAT_VPATCH_offset		11
#define GRID_CLASS_HEARTBEAT_VPATCH_length		2

// HEARTBEAT
#define GRID_CLASS_SERIALNUMBER_code			0x011
#define GRID_CLASS_SERIALNUMBER_frame			"%c%03x_................................%c",GRID_CONST_STX,GRID_CLASS_SERIALNUMBER_code,GRID_CONST_ETX

#define GRID_CLASS_SERIALNUMBER_WORD0_offset		5
#define GRID_CLASS_SERIALNUMBER_WORD0_length		8

#define GRID_CLASS_SERIALNUMBER_WORD1_offset		13
#define GRID_CLASS_SERIALNUMBER_WORD1_length		8

#define GRID_CLASS_SERIALNUMBER_WORD2_offset		21
#define GRID_CLASS_SERIALNUMBER_WORD2_length		8

#define GRID_CLASS_SERIALNUMBER_WORD3_offset		29
#define GRID_CLASS_SERIALNUMBER_WORD3_length		8




// DEBUGTEXT
#define GRID_CLASS_DEBUGTEXT_code					0x020
#define GRID_CLASS_DEBUGTEXT_frame_start			"%c%03xe",GRID_CONST_STX,GRID_CLASS_DEBUGTEXT_code
#define GRID_CLASS_DEBUGTEXT_frame_end				"%c",GRID_CONST_ETX


// BANK
#define GRID_CLASS_BANKACTIVE_code			0x030
#define GRID_CLASS_BANKACTIVE_format		"%c%03x%01x%02x%c",GRID_CONST_STX,GRID_CLASS_BANKACTIVE_code,instruction,banknumber,GRID_CONST_ETX
#define GRID_CLASS_BANKACTIVE_frame			"%c%03x_..%c",GRID_CONST_STX,GRID_CLASS_BANKACTIVE_code,GRID_CONST_ETX

#define GRID_CLASS_BANKACTIVE_BANKNUMBER_offset		5
#define GRID_CLASS_BANKACTIVE_BANKNUMBER_length		2

#define GRID_CLASS_BANKENABLED_code			0x031
#define GRID_CLASS_BANKENABLED_frame		"%c%03x_....%c",GRID_CONST_STX,GRID_CLASS_BANKENABLED_code,GRID_CONST_ETX	

#define GRID_CLASS_BANKENABLED_BANKNUMBER_offset		5
#define GRID_CLASS_BANKENABLED_BANKNUMBER_length		2

#define GRID_CLASS_BANKENABLED_ISENABLED_offset			7
#define GRID_CLASS_BANKENABLED_ISENABLED_length			2

#define GRID_CLASS_BANKCOLOR_code			0x032
#define GRID_CLASS_BANKCOLOR_frame			"%c%03x_........%c",GRID_CONST_STX,GRID_CLASS_BANKCOLOR_code,GRID_CONST_ETX

#define GRID_CLASS_BANKCOLOR_NUM_offset		5
#define GRID_CLASS_BANKCOLOR_NUM_length		2

#define GRID_CLASS_BANKCOLOR_RED_offset		7
#define GRID_CLASS_BANKCOLOR_RED_length		2

#define GRID_CLASS_BANKCOLOR_GRE_offset		9
#define GRID_CLASS_BANKCOLOR_GRE_length		2

#define GRID_CLASS_BANKCOLOR_BLU_offset		11
#define GRID_CLASS_BANKCOLOR_BLU_length		2


// LED SET PHASE

#define GRID_CLASS_LEDPHASE_code			0x040
#define GRID_CLASS_LEDPHASE_format			"%c%03x%01x%02x%02x%02x%c",GRID_CONST_STX,GRID_CLASS_LEDPHASE_code,instruction,layernumber,lednumber,phase,GRID_CONST_ETX
#define GRID_CLASS_LEDPHASE_frame			"%c%03x_......%c",GRID_CONST_STX,GRID_CLASS_LEDPHASE_code,GRID_CONST_ETX

#define GRID_CLASS_LEDPHASE_NUM_offset		5
#define GRID_CLASS_LEDPHASE_NUM_length		2

#define GRID_CLASS_LEDPHASE_LAY_offset		7
#define GRID_CLASS_LEDPHASE_LAY_length		2

#define GRID_CLASS_LEDPHASE_PHA_offset		9
#define GRID_CLASS_LEDPHASE_PHA_length		2

// LED SET COLOR

#define GRID_CLASS_LEDCOLOR_code			0x041
#define GRID_CLASS_LEDCOLOR_format			"%c%03x%01x%02x%02x%02x%02x%02x%c",GRID_CONST_STX,GRID_CLASS_LEDPHASE_code,instruction,layernumber,lednumber,red,gre,blu,GRID_CONST_ETX
#define GRID_CLASS_LEDCOLOR_frame			"%c%03x_..........%c",GRID_CONST_STX,GRID_CLASS_LEDCOLOR_code,GRID_CONST_ETX

#define GRID_CLASS_LEDCOLOR_NUM_offset		5
#define GRID_CLASS_LEDCOLOR_NUM_length		2

#define GRID_CLASS_LEDCOLOR_LAY_offset		7
#define GRID_CLASS_LEDCOLOR_LAY_length		2

#define GRID_CLASS_LEDCOLOR_RED_offset		9
#define GRID_CLASS_LEDCOLOR_RED_length		2

#define GRID_CLASS_LEDCOLOR_GRE_offset		11
#define GRID_CLASS_LEDCOLOR_GRE_length		2

#define GRID_CLASS_LEDCOLOR_BLU_offset		13
#define GRID_CLASS_LEDCOLOR_BLU_length		2


// TEMPLATE PARAMETER DEFINITIONS


#define GRID_TEMPLATE_A_PARAMETER_LIST_LENGTH    8

enum grid_template_a_parameter_index_t {
	
	GRID_TEMPLATE_A_PARAMETER_CONTROLLER_NUMBER,
	GRID_TEMPLATE_A_PARAMETER_CONTROLLER_NUMBER_REVERSED,
	GRID_TEMPLATE_A_PARAMETER_CONTROLLER_AV7,
	GRID_TEMPLATE_A_PARAMETER_CONTROLLER_AV8,
	GRID_TEMPLATE_A_PARAMETER_CONTROLLER_AV14U,
	GRID_TEMPLATE_A_PARAMETER_CONTROLLER_AV14L,
	GRID_TEMPLATE_A_PARAMETER_CONTROLLER_DV7,
	GRID_TEMPLATE_A_PARAMETER_CONTROLLER_DV8,
	
};


#define GRID_TEMPLATE_B_PARAMETER_LIST_LENGTH    6

enum grid_template_b_parameter_index_t {
	
	GRID_TEMPLATE_B_PARAMETER_BANK_NUMBER_ACTIVE,
	GRID_TEMPLATE_B_PARAMETER_BANK_COLOR_RED,
	GRID_TEMPLATE_B_PARAMETER_BANK_COLOR_GRE,
	GRID_TEMPLATE_B_PARAMETER_BANK_COLOR_BLU,
	
	GRID_TEMPLATE_B_PARAMETER_MAPMODE_STATE,
	GRID_TEMPLATE_B_PARAMETER_BANK_NEXT,
	
	
};



#define GRID_PARAMETER_TEMPLATEINDEX_CNUMBER_code		"A0"
#define GRID_PARAMETER_TEMPLATEINDEX_CNUMBERREV_code	"A1"
#define GRID_PARAMETER_TEMPLATEINDEX_AV7_code			"A2"
#define GRID_PARAMETER_TEMPLATEINDEX_AV8_code			"A3"
#define GRID_PARAMETER_TEMPLATEINDEX_AV14U_code			"A4"
#define GRID_PARAMETER_TEMPLATEINDEX_AV14L_code			"A5"
#define GRID_PARAMETER_TEMPLATEINDEX_DV7_code			"A6"
#define GRID_PARAMETER_TEMPLATEINDEX_DV8_code			"A7"

#define GRID_PARAMETER_TEMPLATEINDEX_BANKNUM_code	    "B0"
#define GRID_PARAMETER_TEMPLATEINDEX_BANKRED_code	    "B1"
#define GRID_PARAMETER_TEMPLATEINDEX_BANKGRE_code	    "B2"
#define GRID_PARAMETER_TEMPLATEINDEX_BANKBLU_code	    "B3"
#define GRID_PARAMETER_TEMPLATEINDEX_MAPSTATE_code	    "B4"
#define GRID_PARAMETER_TEMPLATEINDEX_BANKNEXT_code	    "B5"



enum grid_ui_element_t {
	
	GRID_UI_ELEMENT_SYSTEM,
	GRID_UI_ELEMENT_POTENTIOMETER,
	GRID_UI_ELEMENT_BUTTON,
	GRID_UI_ELEMENT_ENCODER,
	
};

#define GRID_PARAMETER_ELEMENTTYPE_SYSTEM_code			"00"
#define GRID_PARAMETER_ELEMENTTYPE_POTENTIOMETER_code	"01"
#define GRID_PARAMETER_ELEMENTTYPE_BUTTON_code			"02"
#define GRID_PARAMETER_ELEMENTTYPE_ENCODER_code			"03"


enum grid_ui_event_t {
	
	GRID_UI_EVENT_INIT,
		
	
	GRID_UI_EVENT_AVC7,
	GRID_UI_EVENT_RVC7,
	GRID_UI_EVENT_DVC,
	GRID_UI_EVENT_DP,
	GRID_UI_EVENT_DR,
	GRID_UI_EVENT_DD,
	
	GRID_UI_EVENT_MAPMODE_PRESS,
	GRID_UI_EVENT_MAPMODE_RELEASE,
	
	
	
	GRID_UI_EVENT_CFG_RESPONSE,
	GRID_UI_EVENT_CFG_REQUEST,
	GRID_UI_EVENT_CFG_EDITOR,
	
	GRID_UI_EVENT_HEARTBEAT,
	
};

#define GRID_PARAMETER_EVENT_INIT		0
#define GRID_PARAMETER_EVENT_AVC7		1
#define GRID_PARAMETER_EVENT_RVC7		2
#define GRID_PARAMETER_EVENT_DVC		3
#define GRID_PARAMETER_EVENT_DP			4
#define GRID_PARAMETER_EVENT_DR			5
#define GRID_PARAMETER_EVENT_DD			6
#define GRID_PARAMETER_EVENT_MP			7
#define GRID_PARAMETER_EVENT_MR			8
#define GRID_PARAMETER_EVENT_CFG_RES	9
#define GRID_PARAMETER_EVENT_CFG_REQ	10
#define GRID_PARAMETER_EVENT_CFG_EDITOR 11

// BANK + ELEMENT TYPE + ELEMENT NUMBER + EVENT TYPE + PARAMETER


#define GRID_EVENTSTRING_HEARTBEAT		"\x02""050eB0000100\x03"

#define GRID_EVENTSTRING_AVC7_POT		"\x02""050eB0A002A2\x03"

#define GRID_EVENTSTRING_DP_BUT			"\x02""050eB0A004A6\x03"
#define GRID_EVENTSTRING_DR_BUT			"\x02""050eB0A005A6\x03"

#define GRID_EVENTSTRING_AVC7_ENC		"\x02""050eB0A001A2\x03"
#define GRID_EVENTSTRING_DP_ENC			"\x02""050eB0A004A6\x03"
#define GRID_EVENTSTRING_DR_ENC			"\x02""050eB0A005A6\x03"


#define GRID_EVENTSTRING_INIT			"\x02""050eB0A00000\x03"





#define GRID_EVENTSTRING_MAPMODE_PRESS		"\x02""050eB00008B4\x03"
#define GRID_EVENTSTRING_MAPMODE_RELEASE	"\x02""050eB00009B4\x03"

#define GRID_EVENTSTRING_CFG_RESPONES		"\x02""050eB0000aB4\x03"
#define GRID_EVENTSTRING_CFG_REQUEST		"\x02""050eB0000bB4\x03"


// DEFAULT ACTION:                     FIRST MIDI then LED_SET_PHASE

#define GRID_ACTIONSTRING_INIT				"\x02""041eA001B1B2B3\x03"
#define GRID_ACTIONSTRING_INIT_ENC			"\x02""041eA001B1B2B3\x03\x02""041eA002B1B2B3\x03""\x02""040eA001A3\x03"

#define GRID_ACTIONSTRING_AVC7				"\x02""000e00b0A0A2\x03\x02""040eA001A3\x03"
#define GRID_ACTIONSTRING_DP				"\x02""000e0090A0A6\x03\x02""040eA001A7\x03"
#define GRID_ACTIONSTRING_DR				"\x02""000e0080A0A6\x03\x02""040eA001A7\x03"

#define GRID_ACTIONSTRING_DP_ENC			"\x02""000e0090A0A6\x03\x02""040eA002A7\x03"
#define GRID_ACTIONSTRING_DR_ENC			"\x02""000e0080A0A6\x03\x02""040eA002A7\x03"

#define GRID_ACTIONSTRING_AVC7_ENC			"\x02""000e00b0A0A2\x03\x02""040eA001A3\x03"


#define GRID_ACTIONSTRING_MAPMODE_PRESS		"\x02""030eB5\x03"
#define GRID_ACTIONSTRING_MAPMODE_RELEASE	""

#define GRID_ACTIONSTRING_CFG_RESPONSE		"\x02""030eB0\x03"
#define GRID_ACTIONSTRING_CFG_REQUEST 		"\x02""030fB0\x03"


#define GRID_CLASS_EVENT_code						0x050
#define GRID_CLASS_EVENT_frame						"%c%03x_........%c",GRID_CONST_STX,GRID_CLASS_EVENT_code,GRID_CONST_ETX

#define GRID_CLASS_EVENT_BANKNUMBER_offset				5
#define GRID_CLASS_EVENT_BANKNUMBER_length				2

#define GRID_CLASS_EVENT_ELEMENTNUMBER_offset			7
#define GRID_CLASS_EVENT_ELEMENTNUMBER_length			2

#define GRID_CLASS_EVENT_EVENTTYPE_offset				9
#define GRID_CLASS_EVENT_EVENTTYPE_length				2

#define GRID_CLASS_EVENT_EVENTPARAM_offset				11
#define GRID_CLASS_EVENT_EVENTPARAM_length				2


#define GRID_CLASS_GLOBALSTORE_code					0x060
#define GRID_CLASS_GLOBALSTORE_frame				"%c%03xe%c",GRID_CONST_STX,GRID_CLASS_GLOBALSTORE_code,GRID_CONST_ETX

#define GRID_CLASS_GLOBALLOAD_code					0x061
#define GRID_CLASS_GLOBALLOAD_frame					"%c%03xe%c",GRID_CONST_STX,GRID_CLASS_GLOBALLOAD_code,GRID_CONST_ETX

#define GRID_CLASS_GLOBALCLEAR_code					0x062
#define GRID_CLASS_GLOBALCLEAR_frame				"%c%03xe%c",GRID_CONST_STX,GRID_CLASS_GLOBALCLEAR_code,GRID_CONST_ETX

#define GRID_CLASS_GLOBALRECALL_code				0x063
#define GRID_CLASS_GLOBALRECALL_frame				"%c%03xe..%c",GRID_CONST_STX,GRID_CLASS_GLOBALRECALL_code,GRID_CONST_ETX

#define GRID_CLASS_GLOBALRECALL_BANKNUMBER_offset	5
#define GRID_CLASS_GLOBALRECALL_BANKNUMBER_length	2

#define GRID_CLASS_LOCALSTORE_code					0x070
#define GRID_CLASS_LOCALSTORE_frame					"%c%03xe%c",GRID_CONST_STX,GRID_CLASS_LOCALSTORE_code,GRID_CONST_ETX

#define GRID_CLASS_LOCALLOAD_code					0x071
#define GRID_CLASS_LOCALLOAD_frame					"%c%03xe%c",GRID_CONST_STX,GRID_CLASS_LOCALLOAD_code,GRID_CONST_ETX

#define GRID_CLASS_LOCALCLEAR_code					0x072
#define GRID_CLASS_LOCALCLEAR_frame					"%c%03xe%c",GRID_CONST_STX,GRID_CLASS_LOCALCLEAR_code,GRID_CONST_ETX


// CONFIG STORE     Fetch(Read) Configure(Overwrite) Append(Write)
#define GRID_CLASS_CONFIGURATION_code						0x080
#define GRID_CLASS_CONFIGURATION_frame						"%c%03x_......%c",GRID_CONST_STX,GRID_CLASS_CONFIGURATION_code,GRID_CONST_ETX
#define GRID_CLASS_CONFIGURATION_frame_start				"%c%03x_......",GRID_CONST_STX,GRID_CLASS_CONFIGURATION_code
#define GRID_CLASS_CONFIGURATION_frame_end					"%c",GRID_CONST_ETX

#define GRID_CLASS_CONFIGURATION_BANKNUMBER_offset			5
#define GRID_CLASS_CONFIGURATION_BANKNUMBER_length			2

#define GRID_CLASS_CONFIGURATION_ELEMENTNUMBER_offset		7
#define GRID_CLASS_CONFIGURATION_ELEMENTNUMBER_length		2

#define GRID_CLASS_CONFIGURATION_EVENTTYPE_offset			9
#define GRID_CLASS_CONFIGURATION_EVENTTYPE_length			2

#define GRID_CLASS_CONFIGURATION_ACTIONSTRING_offset		11
#define GRID_CLASS_CONFIGURATION_ACTIONSTRING_length		0













#endif /* GRID_PROTOCOL_H_INCLUDED */