@startuml test

skinparam Style strictuml
skinparam SequenceMessageAlignment center

Editor <-> Master : ACM Open
rnote over Master
  hb_type
  updated
end note
rnote over Editor
  Port
  opened
end note
...
hnote over Master
 Tick
endhnote
Master -> Editor : Heartbeat
rnote left
  Create Module
  X=0, Y=0
end note
Master -> Grid : Heartbeat
hnote over Grid
  From master?
  Update X, Y
end note
...
hnote over Grid
 Tick
endhnote
Grid -> Master : Heartbeat
Master -> Editor : Heartbeat
rnote left
  Create Module
  X=0, Y=1
end note
...
hnote over Editor
 Tick
endhnote
Editor -> Master : Heartbeat
Master -> Grid : Heartbeat



@enduml