#pragma once

#define GRID_PICO_PIN_SPI_CS 17

// GRID UART PIN CONNECTIONS
#define GRID_PICO_PIN_NORTH_TX 23
#define GRID_PICO_PIN_NORTH_RX 6

#define GRID_PICO_PIN_EAST_TX 26
#define GRID_PICO_PIN_EAST_RX 24

#define GRID_PICO_PIN_SOUTH_TX 2
#define GRID_PICO_PIN_SOUTH_RX 27

#define GRID_PICO_PIN_WEST_TX 5
#define GRID_PICO_PIN_WEST_RX 3

// GRID SYNC PIN CONNECTIONS
#define GRID_PICO_PIN_LED 15
#define GRID_PICO_PIN_SYNC1 25
#define GRID_PICO_PIN_SYNC2 4