name: Build and run unit tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Clang setup
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Run unit tests
        run: ./lua_build.sh && ./test.sh
