# This is a basic workflow that is manually triggered

name: Protocol converter workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    paths:
      - 'grid_common/grid_protocol.h'
      - 'grid_common/grid_ui_system.h'
      - 'grid_common/grid_ui_button.h'
      - 'grid_common/grid_ui_encoder.h'
      - 'grid_common/grid_ui_endless.h'
      - 'grid_common/grid_ui_potmeter.h'
      - 'grid_common/grid_ui_lcd.h'
      - 'grid_common/lua_src/lua_source_collection.h'
      - '.github/workflows/protocol_converter.yml'
      - '.github/workflows/protocol_converter.py'
      - '.github/workflows/documentation_validator.sh'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repository
        run: |
          git --version
          git config --global user.email "bot@intech.studio"
          git config --global user.name "Intech Bot"
          git clone https://${{ secrets.PERSONALACCESSTOKEN }}@github.com/intechstudio/grid-protocol.git
          ls

      - uses: actions/setup-python@v2
      - name: Setup python
        run: |
          python ./.github/workflows/protocol_converter.py ./grid_common/grid_protocol.h,./grid_common/lua_src/lua_source_collection.h,./grid_common/grid_ui_system.h,./grid_common/grid_ui_button.h,./grid_common/grid_ui_encoder.h,./grid_common/grid_ui_endless.h,./grid_common/grid_ui_potmeter.h,./grid_common/grid_ui_lcd.h grid-protocol/src/grid_protocol_bot.json grid-protocol/grid-protocol/lists.py

      - name: Check file
        if: github.ref == 'refs/heads/master'
        run: |
          cd grid-protocol
          cat -v src/grid_protocol_bot.json
          if [[ `git status --porcelain` ]]; then
            git add -A
            git commit -m "BOT protocol file synced from grid-fw repo"
            git push
          fi

      - name: Clone documentation
        if: github.ref == 'refs/heads/master'
        run: |
          git clone https://github.com/intechstudio/grid-documentation.git
          sh ./.github/workflows/documentation_validator.sh >> report.txt
          cat report.txt
