name: Publish stable release

on:
  workflow_call:
    inputs:
      product_name:
        description: "Product name for release naming"
        required: true
        type: string
      version_tag:
        description: "Git tag version for the release"
        required: true
        type: string
      timestamp:
        description: "Build date timestamp"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      product_name:
        description: "Product name for release naming"
        required: true
        type: string
      version_tag:
        description: "Git tag version for the release"
        required: true
        type: string
      timestamp:
        description: "Build date timestamp"
        required: true
        type: string

jobs:
  publish-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release_firmware
          path: release/

      - name: Zip artifacts for github release
        uses: vimtor/action-zip@v1
        with:
          files: release/
          dest: ${{ inputs.product_name }}_release.zip

      - name: Create stable release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version_tag }}
          name: ${{ inputs.product_name }} ${{ inputs.version_tag }} (${{ inputs.timestamp }})
          files: ${{ inputs.product_name }}_release.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
